project:
  type: website
  output-dir: _site
  render:
    - index.ipynb  

website:
  title: "Crime Summary"
  navbar:
    left:
      - text: "Home"
        file: index.ipynb
      
      

format:
  html:
    theme: cosmo
    toc: true
    echo: false  